server.port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
    #show-sql: true
  sql.init.mode: always
  #config.activate.on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:fm
    username: fm
    password: fm
  h2.console.enabled: true

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type: INFO
      orm.jdbc.bind: TRACE
  
  #---
#spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
#spring.datasource.username=shareit
#spring.datasource.password=shareit
#spring.datasource.driver-class-name=org.postgresql.Driver
#  #---
#spring.config.activate.on-profile=ci,test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:shareit
#spring.datasource.username=shareit
#spring.datasource.password=shareit
#spring.h2.console.enabled=true
# todo delete