CREATE TABLE IF NOT EXISTS game_of_team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  team VARCHAR(64) NOT NULL,
  date DATE NOT NULL,
  points INT NOT NULL,
  CONSTRAINT pk_game_of_team PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  home_team_id BIGINT NOT NULL,
  away_team_id BIGINT NOT NULL,
  CONSTRAINT pk_game PRIMARY KEY (id),
  CONSTRAINT fk_home_team_id FOREIGN KEY(home_team_id) REFERENCES game_of_team(id),
  CONSTRAINT fk_away_team_id FOREIGN KEY(away_team_id) REFERENCES game_of_team(id),
  CONSTRAINT uq_home_team_id UNIQUE (home_team_id),
  CONSTRAINT uq_away_team_id UNIQUE (away_team_id)
);